/*
 Navicat Premium Data Transfer

 Source Server         : oracle19C
 Source Server Type    : Oracle
 Source Server Version : 190000
 Source Host           : localhost:1521
 Source Schema         : SYSTEMDESIGNER

 Target Server Type    : Oracle
 Target Server Version : 190000
 File Encoding         : 65001

 Date: 31/05/2022 11:04:34
*/


-- ----------------------------
-- Table structure for administrator
-- ----------------------------
DROP TABLE "SYSTEMDESIGNER"."administrator";
CREATE TABLE "SYSTEMDESIGNER"."administrator" (
  "adminId" NUMBER VISIBLE NOT NULL ,
  "adminAccount" VARCHAR2(20 BYTE) VISIBLE NOT NULL ,
  "adminPassword" VARCHAR2(20 BYTE) VISIBLE NOT NULL ,
  "adminRegisterTime" DATE VISIBLE NOT NULL ,
  "adminModifiedTime" DATE VISIBLE 
)
TABLESPACE "HOMETUTOR"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for OrderInfo
-- ----------------------------
DROP TABLE "SYSTEMDESIGNER"."OrderInfo";
CREATE TABLE "SYSTEMDESIGNER"."OrderInfo" (
  "orderId" NUMBER VISIBLE NOT NULL ,
  "parentId" NUMBER VISIBLE NOT NULL ,
  "adminId" NUMBER VISIBLE NOT NULL ,
  "teacherId" NUMBER VISIBLE NOT NULL ,
  "orderStatus" NUMBER VISIBLE NOT NULL ,
  "serviceTime" VARCHAR2(30 BYTE) VISIBLE NOT NULL ,
  "demand" VARCHAR2(20 BYTE) VISIBLE NOT NULL ,
  "concreteDemand" VARCHAR2(255 BYTE) VISIBLE NOT NULL ,
  "createTime" DATE VISIBLE ,
  "startTime" DATE VISIBLE ,
  "endTime" DATE VISIBLE ,
  "locateAddress" VARCHAR2(50 BYTE) VISIBLE NOT NULL ,
  "childInfo" VARCHAR2(50 BYTE) VISIBLE NOT NULL ,
  "price" NUMBER VISIBLE ,
  "review" FLOAT(126) VISIBLE ,
  "orderInfoModifyTime" DATE VISIBLE 
)
TABLESPACE "HOMETUTOR"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for parent&child
-- ----------------------------
DROP TABLE "SYSTEMDESIGNER"."parent&child";
CREATE TABLE "SYSTEMDESIGNER"."parent&child" (
  "parentId" NUMBER VISIBLE NOT NULL ,
  "childName" VARCHAR2(20 BYTE) VISIBLE NOT NULL ,
  "childAge" NUMBER VISIBLE NOT NULL ,
  "phoneNumber" VARCHAR2(11 BYTE) VISIBLE NOT NULL ,
  "locateAddress" VARCHAR2(50 BYTE) VISIBLE NOT NULL ,
  "parentAccountStatus" NUMBER VISIBLE ,
  "parentOpenId" VARCHAR2(50 BYTE) VISIBLE ,
  "parentAccount" NUMBER VISIBLE ,
  "parentInfoModifyTime" DATE VISIBLE ,
  "parentRegisterTime" DATE VISIBLE 
)
TABLESPACE "HOMETUTOR"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for teacher
-- ----------------------------
DROP TABLE "SYSTEMDESIGNER"."teacher";
CREATE TABLE "SYSTEMDESIGNER"."teacher" (
  "teacherId" NUMBER VISIBLE NOT NULL ,
  "gender" NUMBER VISIBLE NOT NULL ,
  "name" VARCHAR2(12 BYTE) VISIBLE NOT NULL ,
  "age" NUMBER VISIBLE NOT NULL ,
  "phoneNumber" VARCHAR2(11 BYTE) VISIBLE ,
  "school" VARCHAR2(30 BYTE) VISIBLE NOT NULL ,
  "photo" VARCHAR2(200 BYTE) VISIBLE ,
  "introduction" CLOB VISIBLE ,
  "review_score" FLOAT(126) VISIBLE ,
  "register_time" DATE VISIBLE ,
  "last_modified_time" DATE VISIBLE ,
  "teacherAccountStatus" NUMBER VISIBLE ,
  "openid" VARCHAR2(50 BYTE) VISIBLE ,
  "teacherAccount" NUMBER VISIBLE 
)
TABLESPACE "HOMETUTOR"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Primary Key structure for table administrator
-- ----------------------------
ALTER TABLE "SYSTEMDESIGNER"."administrator" ADD CONSTRAINT "PK_ADMINISTRATOR" PRIMARY KEY ("adminId");

-- ----------------------------
-- Checks structure for table administrator
-- ----------------------------
ALTER TABLE "SYSTEMDESIGNER"."administrator" ADD CONSTRAINT "SYS_C007523" CHECK ("adminId" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."administrator" ADD CONSTRAINT "SYS_C007524" CHECK ("adminAccount" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."administrator" ADD CONSTRAINT "SYS_C007525" CHECK ("adminPassword" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."administrator" ADD CONSTRAINT "SYS_C007526" CHECK ("adminRegisterTime" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table OrderInfo
-- ----------------------------
ALTER TABLE "SYSTEMDESIGNER"."OrderInfo" ADD CONSTRAINT "PK_ORDERINFO" PRIMARY KEY ("orderId");

-- ----------------------------
-- Checks structure for table OrderInfo
-- ----------------------------
ALTER TABLE "SYSTEMDESIGNER"."OrderInfo" ADD CONSTRAINT "SYS_C007520" CHECK ("orderId" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."OrderInfo" ADD CONSTRAINT "SYS_C007521" CHECK ("orderStatus" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."OrderInfo" ADD CONSTRAINT "SYS_C007543" CHECK ("parentId" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."OrderInfo" ADD CONSTRAINT "SYS_C007544" CHECK ("adminId" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."OrderInfo" ADD CONSTRAINT "SYS_C007545" CHECK ("teacherId" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."OrderInfo" ADD CONSTRAINT "SYS_C007546" CHECK ("serviceTime" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."OrderInfo" ADD CONSTRAINT "SYS_C007547" CHECK ("demand" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."OrderInfo" ADD CONSTRAINT "SYS_C007548" CHECK ("concreteDemand" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."OrderInfo" ADD CONSTRAINT "SYS_C007549" CHECK ("locateAddress" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."OrderInfo" ADD CONSTRAINT "SYS_C007550" CHECK ("childInfo" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table OrderInfo
-- ----------------------------
CREATE INDEX "SYSTEMDESIGNER"."oneTomany2_FK"
  ON "SYSTEMDESIGNER"."OrderInfo" ("adminId" ASC)
  LOGGING
  TABLESPACE "HOMETUTOR"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "SYSTEMDESIGNER"."oneTomany3_FK"
  ON "SYSTEMDESIGNER"."OrderInfo" ("parentId" ASC)
  LOGGING
  TABLESPACE "HOMETUTOR"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
CREATE INDEX "SYSTEMDESIGNER"."oneTomany_1_FK"
  ON "SYSTEMDESIGNER"."OrderInfo" ("teacherId" ASC)
  LOGGING
  TABLESPACE "HOMETUTOR"
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;

-- ----------------------------
-- Primary Key structure for table parent&child
-- ----------------------------
ALTER TABLE "SYSTEMDESIGNER"."parent&child" ADD CONSTRAINT "PK_PARENT&CHILD" PRIMARY KEY ("parentId");

-- ----------------------------
-- Checks structure for table parent&child
-- ----------------------------
ALTER TABLE "SYSTEMDESIGNER"."parent&child" ADD CONSTRAINT "SYS_C007528" CHECK ("parentId" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."parent&child" ADD CONSTRAINT "SYS_C007529" CHECK ("childName" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."parent&child" ADD CONSTRAINT "SYS_C007530" CHECK ("childAge" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."parent&child" ADD CONSTRAINT "SYS_C007531" CHECK ("phoneNumber" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."parent&child" ADD CONSTRAINT "SYS_C007532" CHECK ("locateAddress" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table teacher
-- ----------------------------
ALTER TABLE "SYSTEMDESIGNER"."teacher" ADD CONSTRAINT "PK_TEACHER" PRIMARY KEY ("teacherId");

-- ----------------------------
-- Checks structure for table teacher
-- ----------------------------
ALTER TABLE "SYSTEMDESIGNER"."teacher" ADD CONSTRAINT "SYS_C007534" CHECK ("teacherId" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."teacher" ADD CONSTRAINT "SYS_C007535" CHECK ("gender" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."teacher" ADD CONSTRAINT "SYS_C007536" CHECK ("name" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."teacher" ADD CONSTRAINT "SYS_C007537" CHECK ("age" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."teacher" ADD CONSTRAINT "SYS_C007538" CHECK ("school" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table OrderInfo
-- ----------------------------
ALTER TABLE "SYSTEMDESIGNER"."OrderInfo" ADD CONSTRAINT "FK_ORDERINF_ONETOMANY_ADMINIST" FOREIGN KEY ("adminId") REFERENCES "SYSTEMDESIGNER"."administrator" ("adminId") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."OrderInfo" ADD CONSTRAINT "FK_ORDERINF_ONETOMANY_PARENT&C" FOREIGN KEY ("parentId") REFERENCES "SYSTEMDESIGNER"."parent&child" ("parentId") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SYSTEMDESIGNER"."OrderInfo" ADD CONSTRAINT "FK_ORDERINF_ONETOMANY_TEACHER" FOREIGN KEY ("teacherId") REFERENCES "SYSTEMDESIGNER"."teacher" ("teacherId") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
